# Generated by Django 6.0.3 on 2026-06-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
